files: ^(zpp_rtos/)|^(zpp_include/)|^(zpp_drivers/)
exclude: .*\.(yaml|conf|overlay|txt)$|(Kconfig)$
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  -   id: check-yaml
      args: [--allow-multiple-documents]
  -   id: end-of-file-fixer
  -   id: trailing-whitespace
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: 'v21.1.1'
  hooks:
  -   id: clang-format
- repo: https://github.com/cpplint/cpplint
  rev: '2.0.2'
  hooks:
  -   id: cpplint
- repo: local
  hooks:
  -   id: lizard
      name: lizard
      entry: lizard
      language: system
      args: [-C 12]
#- repo: https://github.com/pocc/pre-commit-hooks
#  rev: master
#  hooks:
#  -   id: cppcheck
#      entry: cppcheck --enable=all --suppress=missingInclude:* --inline-suppr -i mbed-os --error-exitcode=1
- repo: local
  hooks:
  -   id: cppcheck
      name: cppcheck
      require_serial: true
      entry: cppcheck --enable=all --suppressions-list=cppcheck_suppressions.txt --inline-suppr -i ../zephyr --std=c++14 --error-exitcode=1 -v -DCONFIG_NUM_PREEMPT_PRIORITIES=8
      language: system

