repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  -   id: check-yaml
      files: \.(yaml|yml)$
      args: [--allow-multiple-documents]
  -   id: end-of-file-fixer
      files: \.(c|cc|cpp|cxx|h|hpp|hxx)$
  -   id: trailing-whitespace
      files: \.(c|cc|cpp|cxx|h|hpp|hxx)$
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: 'v22.1.5'
  hooks:
  - id: clang-format
    files: \.(c|cc|cpp|cxx|h|hpp|hxx)$  
- repo: local
  hooks:
  - id: copyright
    name: Check copyright
    entry: python scripts/check_copyright.py
    language: system
    pass_filenames: true
    files: \.(c|cc|cpp|cxx|h|hpp|hxx)$    
- repo: local
  hooks:
  - id: clang-tidy-test-mutex
    name: clang-tidy-test-mutex
    entry: python scripts/run_clang_tidy.py --app zpp_rtos/tests/mutex --spec "test" --wd "."
    language: system
    pass_filenames: true
    files: ^(zpp_rtos/tests/mutex)/.*\.(c|cc|cpp|cxx)$
  - id: clang-tidy-test-semaphore
    name: clang-tidy-test-semaphore
    entry: python scripts/run_clang_tidy.py --app zpp_rtos/tests/semaphore --spec "test" --wd "."
    language: system
    pass_filenames: true
    files: ^(zpp_rtos/tests/semaphore)/.*\.(c|cc|cpp|cxx)$
  - id: clang-tidy-test-thread
    name: clang-tidy-test-thread
    entry: python scripts/run_clang_tidy.py --app zpp_rtos/tests/thread --spec "test+log" --wd "."
    language: system
    pass_filenames: true
    files: ^(zpp_rtos/tests/thread)/.*\.(c|cc|cpp|cxx)$
  - id: clang-tidy-test-interrupt-in
    name: clang-tidy-test-interrupt-in
    entry: python scripts/run_clang_tidy.py --app zpp_drivers/tests/interrupt_in --spec "test+gpio" --wd "."
    language: system
    pass_filenames: true
    files: ^(zpp_drivers/tests/interrupt_in)/.*\.(c|cc|cpp|cxx)$