# C++ support
CONFIG_CPP=y
CONFIG_REQUIRES_FULL_LIBCPP=y
CONFIG_STD_CPP20=y

# we use zpp_lib
CONFIG_USE_ZPP_LIB=y

# fully disable logging
CONFIG_LOG=n
CONFIG_BOOT_BANNER=n

# increase the stack size of the main thread
CONFIG_MAIN_STACK_SIZE=2048

# compiler warnings must be treated as errors
CONFIG_COMPILER_WARNINGS_AS_ERRORS=y