# enable static scheduling with event
CONFIG_BIKE_COMPUTER_STATIC_SCHEDULING_WITH_EVENT=y

# increase the stack size of the threads created with zpp_lib
CONFIG_ZPP_THREAD_STACK_SIZE=4096

# increase the stack size of the main thread
CONFIG_MAIN_STACK_SIZE=4096
