name: Test zpp_lib

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      sdk_version:
        description: "Zephyr SDK version"
        required: false
        default: "0.17.0"

permissions:
  checks: write
  pull-requests: write
  contents: read

jobs:       
  test:
    runs-on: ubuntu-latest
    env:
      ZEPHYR_MODULES: ${{ github.workspace }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Setup Zephyr
        uses: AdvEmbSof/setup-zephyr-action@v1
        with:
          sdk_version: '0.17.0'
          path_west_workspace: ${{ github.workspace }}/../

      - name: Run twister for zpp_lib on qemu_x86      
        shell: bash
        run: |
          west twister -T zpp_rtos/tests \
            -v -p qemu_x86 \
            --inline-logs \
            --integration \
            --outdir $GITHUB_WORKSPACE/twister-out
            
      - name: Set variables
        if: success() || failure()
        id: vars
        run: |
          echo "branch=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          
      - name: Archive test results
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: aes_${{ steps.vars.outputs.branch }}_${{ steps.vars.outputs.sha_short }}
          path: |
            twister-out/testplan.json
            twister-out/twister_report.xml
            twister-out/twister_suite_report.xml
            twister-out/twister.json
            twister-out/testplan.json
            twister-out/**/*.log

      - name: Publish test results in GitHub UI
        if: success() || failure()
        uses: actions/upload-test-report@v2
        with:
          path: twister-out/twister_report.xml
          
     # - name: Publish test results
     #   if: success() || failure()
     #   uses: EnricoMi/publish-unit-test-result-action@v2
     #   with:
     #     files: twister-out/twister_report.xml
